server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  security:
    oauth2:
      client:
        registration:
          persons-client-oidc:
            provider: spring
            client-id: persons-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: persons-client-oidc
          persons-client-authorization-code:
            provider: spring
            client-id: persons-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: persons.read, persons.write
            client-name: persons-client-authorization-code
          persons-client-client-credentials:
            provider: spring
            client-id: persons-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: persons.read, persons.write
            client-name: persons-client-client-credentials
        provider:
          spring:
            issuer-uri: http://auth-server:9000
#persons:
#  base-uri: http://127.0.0.1:8090/persons
#  main:
#    allow-bean-definition-overriding: true